
name: Atualizar Dashboard

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Commit automático
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git pull
          git commit --allow-empty -m "Atualização automática"
          git push
